import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProviders from "./providers";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Centre de formation",
  description: "Generated by create next app",
  /* icons:{
    icon: "/favicon.ico",
  } */
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="fr"
      className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased`}
    >
      <body className="min-h-screen h-full flex flex-col bg-[#060e6f] bg-[url('/images/bg/bg-blue.png')] bg-cover bg-center bg-scroll text-white bg-no-repeat">
        <AppProviders>
         {children}
         <Toaster/>
        </AppProviders>
      </body>
    </html>
  );
}
